---
- hosts: localhost
  roles:
    - role: '{{ playbook_dir }}'
      # abc_ver: 1.0.1
  tasks:
    # - command: /usr/local/bin/argo
    - command: argo
      register: test_output
    - name: assert binary prints help output
      debug:
        msg: '{{ test_output.stdout }}'
